// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: mtgvujviqdsykxsszyff

class SupabaseConfig {
  static const String supabaseUrl = 'https://mtgvujviqdsykxsszyff.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10Z3Z1anZpcWRzeWt4c3N6eWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1NDE5NDQsImV4cCI6MjA4MDExNzk0NH0.2Uh4w_zf6mB97LFDe8tgSiV9y6NjB16GKnPhW3gWgsE';
}
